# Get Data

In [1]:
# import sys
# sys.path.append("..")
# from nlp.fetch import tweets

## Read Data

In [2]:
import pandas as pd
import numpy as np
import tldextract
import re
from urllib.parse import urlparse
from emoji import UNICODE_EMOJI

In [3]:
tweets_df = pd.read_csv("../data/tweets.csv")

In [4]:
print("Shape of data =>",tweets_df.shape)

Shape of data => (4316, 34)

In [5]:
tweets_df.head()

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1296147154369748993,1296022410462887937,1597860537000,2020-08-19,23:38:57,IST,2494196617,dmytrogladkyi,🇺🇦 Dmytro Gladkyi 💙 Dart Developer Paladin,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '2494196617', 'username': 'Dmytro...",NaN,NaN,NaN,NaN
1,1296146774445428739,1296124399804915712,1597860446000,2020-08-19,23:37:26,IST,1253125001307467776,mycodinghabits,omotola shogunle,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '1253125001307467776', 'username'...",NaN,NaN,NaN,NaN
2,1296146090803290112,1296039839729680384,1597860283000,2020-08-19,23:34:43,IST,763755919,lo_victoria2666,Victoria Lo,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '763755919', 'username': 'lo_vict...",NaN,NaN,NaN,NaN
3,1296144512771698690,1296144512771698690,1597859907000,2020-08-19,23:28:27,IST,1644829458,thatanimeguy23,Shivam bhat,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '1644829458', 'username': 'thatan...",NaN,NaN,NaN,NaN
4,1296143311460282369,1296039839729680384,1597859621000,2020-08-19,23:23:41,IST,199406785,eazyjazz02,Oluwaseun Dabiri,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '199406785', 'username': 'Eazyjaz...",NaN,NaN,NaN,NaN

### Changing dataframe display options

#### Displaying all columns

In [6]:
pd.set_option('display.max_columns',None)
tweets_df.head()

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,tweet,mentions,urls,photos,replies_count,retweets_count,likes_count,hashtags,cashtags,link,retweet,quote_url,video,near,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1296147154369748993,1296022410462887937,1597860537000,2020-08-19,23:38:57,IST,2494196617,dmytrogladkyi,🇺🇦 Dmytro Gladkyi 💙 Dart Developer Paladin,NaN,stopped doing that 2 years ago.\n\nswitched to...,"['giusepe', 'hashnode']",[],[],0,0,2,[],[],https://twitter.com/DmytroGladkyi/status/12961...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '2494196617', 'username': 'Dmytro...",NaN,NaN,NaN,NaN
1,1296146774445428739,1296124399804915712,1597860446000,2020-08-19,23:37:26,IST,1253125001307467776,mycodinghabits,omotola shogunle,NaN,Thank you @iambolajiayo for resharing 😌,"['iambolajiayo', 'hashnode']",[],[],0,0,1,[],[],https://twitter.com/mycodinghabits/status/1296...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '1253125001307467776', 'username'...",NaN,NaN,NaN,NaN
2,1296146090803290112,1296039839729680384,1597860283000,2020-08-19,23:34:43,IST,763755919,lo_victoria2666,Victoria Lo,NaN,My pleasure~,"['eazyjazz02', 'hashnode']",[],[],0,0,0,[],[],https://twitter.com/lo_victoria2666/status/129...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '763755919', 'username': 'lo_vict...",NaN,NaN,NaN,NaN
3,1296144512771698690,1296144512771698690,1597859907000,2020-08-19,23:28:27,IST,1644829458,thatanimeguy23,Shivam bhat,NaN,Day 63:\n\n#100DaysOfCode\n#hashnode\n\nI got ...,[],[],[],1,5,6,"['#100daysofcode', '#hashnode']",[],https://twitter.com/thatanimeguy23/status/1296...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '1644829458', 'username': 'thatan...",NaN,NaN,NaN,NaN
4,1296143311460282369,1296039839729680384,1597859621000,2020-08-19,23:23:41,IST,199406785,eazyjazz02,Oluwaseun Dabiri,NaN,thank you so much for the article,"['lo_victoria2666', 'hashnode']",[],[],1,0,2,[],[],https://twitter.com/Eazyjazz02/status/12961433...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '199406785', 'username': 'Eazyjaz...",NaN,NaN,NaN,NaN

#### Changing width

In [7]:
pd.set_option('max_colwidth',None)
tweets_df.head()

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,tweet,mentions,urls,photos,replies_count,retweets_count,likes_count,hashtags,cashtags,link,retweet,quote_url,video,near,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1296147154369748993,1296022410462887937,1597860537000,2020-08-19,23:38:57,IST,2494196617,dmytrogladkyi,🇺🇦 Dmytro Gladkyi 💙 Dart Developer Paladin,NaN,stopped doing that 2 years ago.\n\nswitched to @hashnode! I now own all my markdown articles source code,"['giusepe', 'hashnode']",[],[],0,0,2,[],[],https://twitter.com/DmytroGladkyi/status/1296147154369748993,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '2494196617', 'username': 'DmytroGladkyi'}, {'user_id': '28221495', 'username': 'giusepe'}, {'user_id': '3957817872', 'username': 'hashnode'}]",NaN,NaN,NaN,NaN
1,1296146774445428739,1296124399804915712,1597860446000,2020-08-19,23:37:26,IST,1253125001307467776,mycodinghabits,omotola shogunle,NaN,Thank you @iambolajiayo for resharing 😌,"['iambolajiayo', 'hashnode']",[],[],0,0,1,[],[],https://twitter.com/mycodinghabits/status/1296146774445428739,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '1253125001307467776', 'username': 'mycodinghabits'}, {'user_id': '890634172716527616', 'username': 'iambolajiayo'}, {'user_id': '3957817872', 'username': 'hashnode'}]",NaN,NaN,NaN,NaN
2,1296146090803290112,1296039839729680384,1597860283000,2020-08-19,23:34:43,IST,763755919,lo_victoria2666,Victoria Lo,NaN,My pleasure~,"['eazyjazz02', 'hashnode']",[],[],0,0,0,[],[],https://twitter.com/lo_victoria2666/status/1296146090803290112,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '763755919', 'username': 'lo_victoria2666'}, {'user_id': '199406785', 'username': 'Eazyjazz02'}, {'user_id': '3957817872', 'username': 'hashnode'}]",NaN,NaN,NaN,NaN
3,1296144512771698690,1296144512771698690,1597859907000,2020-08-19,23:28:27,IST,1644829458,thatanimeguy23,Shivam bhat,NaN,"Day 63:\n\n#100DaysOfCode\n#hashnode\n\nI got so fed up with coding since i got stuck with a problem and for past few days... I didn't feel like coding at all as i didn't understand the flow. so instead of wasting my time , I switched to writing blog for a while.",[],[],[],1,5,6,"['#100daysofcode', '#hashnode']",[],https://twitter.com/thatanimeguy23/status/1296144512771698690,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '1644829458', 'username': 'thatanimeguy23'}]",NaN,NaN,NaN,NaN
4,1296143311460282369,1296039839729680384,1597859621000,2020-08-19,23:23:41,IST,199406785,eazyjazz02,Oluwaseun Dabiri,NaN,thank you so much for the article,"['lo_victoria2666', 'hashnode']",[],[],1,0,2,[],[],https://twitter.com/Eazyjazz02/status/1296143311460282369,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '199406785', 'username': 'Eazyjazz02'}, {'user_id': '763755919', 'username': 'lo_victoria2666'}, {'user_id': '3957817872', 'username': 'hashnode'}]",NaN,NaN,NaN,NaN

In [8]:
tweets_df["tweet"].sample(10)

742                                                                                                                                                                                                                                                                                                                                                                                                                    http://Dev.to  vs hashnode?
2134                                                                                                                                                                                                     My Favorite JavaScript Tips and Tricks\n{ by @tapasadhikary } from @hashnode\n#2articles1week #javascript #webdevelopment #beginner #tips https://blog.greenroots.info/my-favorite-javascript-tips-and-tricks-ckd60i4cq011em8s16uobcelc …
426                                                                                                                                                                                                                                                                                                                                                                                                                                    +1 hashnode
1114                                                                                                                                                                                                                                                                                                                                                                                                                                     Good one!
852                                                                                                                                                                                                                                                                                                                                          what if I just republish the exact same article with the origin url of the other blog? different URLs
530                                                                                                                                                                                                                                                                                                                                                                                                             Follow the steps in the blog post.
3805    Thank you so much for this piece DollyPee , it's really inspiring\n_________________\nWhy I decided to learn front end web development \n{ by @Dolapo_writes } from @hashnode\n#webdevelopment #frontenddevelopment #webdev #content #tech https://hashnode.com/post/why-i-decided-to-learn-front-end-web-development-one-year-after-i-had-started-my-freelancing-career-as-a-copywriter-and-content-developer-ckc9mpqh700amlqs17tegg4i0 …
2361                                                                                                                                                                                                                                                                          Just created a new blog using @hashnode. It's fast ⚡️, free 🎉, and highly customisable ⚙️. Get yours here:  https://hashnode.com \n🌎:  https://manthan.hashnode.dev
4134                                                                                                                                                                                                                                                                                                                                                                                     I've got questions for you but that would be on whatsapp.
1055                                                                                                                                                                                                    Postwoman is changing name 🛸\n{ by @liyasthomas } from @hashnode\n#devblogging #webdevelopment #apis #testing #HashnodeCommunity #HashnodeGiveaway https://liyasthomas.hashnode.dev/postwoman-is-changing-name-ckdqrqwoe03prl9s11qnraryd …
Name: tweet, dtype: object

In [9]:
tweets_df["urls"].sample(10)

4111                                                                                      []
668                                                                                       []
3050                                                                                      []
3966    ['https://yomaokobiah.com/arduino-starter-kit-project-02-ckc3ro1w50036tqs12s0ze78v']
3557                                                                                      []
889                                                                                       []
640                                                                                       []
1812                                                                                      []
476                        ['https://cakebaby.dev/youve-got-this-ckcnhcgr400c8fqs1cdu49gpf']
2748                         ['https://twitter.com/iambolajiayo/status/1154354178141110272']
Name: urls, dtype: object

In [10]:
tweets_df["hashtags"].sample(10)

2689                                                                     []
2244                    ['#2articles1week', '#2articles1week', '#hashnode']
708                   ['#opensource', '#kubernetes', '#baremetal', '#edge']
3069                                                                     []
570                                                                      []
3762                                                                     []
3557                                                                     []
4182                                                                     []
2953    ['#developertools', '#commandline', '#terminal', '#2articles1week']
3224                                                                     []
Name: hashtags, dtype: object

## Unnest nested columns

In [11]:
drop_columns = [
    "place",
    "photos",
    "cashtags",
    "retweet",
    "quote_url",
    "video",
    "near",
    "geo",
    "source",
    "user_rt_id",
    "user_rt",
    "retweet_id",
    "reply_to",
    "retweet_date",
    "translate",
    "trans_src",
    "trans_dest"]

tweets_df.drop(columns=drop_columns, inplace=True)
tweets_df.drop_duplicates(inplace=True)

In [12]:
tweets_df["hashtags"].str.replace("'","").str.strip('[]').str.split(',')

0                                              []
1                                              []
2                                              []
3                    [#100daysofcode,  #hashnode]
4                                              []
                          ...
4311                      [#reactjs,  #templates]
4312                                           []
4313    [#100daysofgads2020,  #100daysofgads2020]
4314                                           []
4315                                           []
Name: hashtags, Length: 4316, dtype: object

In [13]:
tweets_df["hashtags"] = tweets_df["hashtags"].str.replace("'","").str.strip('[]').str.split(',')
tweets_df["mentions"] = tweets_df["mentions"].str.replace("'","").str.strip('[]').str.split(',')
tweets_df["urls"] = tweets_df["urls"].str.replace("'","").str.strip('[]').str.split(',')

In [14]:
tweets_df["created_at"]

0       1597860537000
1       1597860446000
2       1597860283000
3       1597859907000
4       1597859621000
            ...
4311    1592983226000
4312    1592979639000
4313    1592942983000
4314    1592937475000
4315    1592937018000
Name: created_at, Length: 4316, dtype: int64

In [15]:
pd.to_datetime(tweets_df.created_at,unit='ms')

tweets_df["created_at"] = pd.to_datetime(tweets_df.created_at,unit='ms')

In [16]:
tweets_df["hashtags_count"] = tweets_df["hashtags"].apply(lambda x: len(x))
tweets_df["mentions_count"] = tweets_df["mentions"].apply(lambda x: len(x))

In [17]:
def unnest(df, tile, explode):
    vals = df[explode].sum(1)
    rs = [len(r) for r in vals]
    a = np.repeat(df[tile].values, rs, axis=0)
    b = np.concatenate(vals.values)
    d = np.column_stack((a, b))
    return pd.DataFrame(d, columns = tile +  explode)

In [18]:
df_unnest_hashtags = unnest(tweets_df, list(tweets_df.columns.difference(['hashtags'])),['hashtags'])
df_unnest_hashtags["hashtags"].replace('', np.nan, inplace=True)
df_unnest_hashtags.dropna(how='any', subset=["hashtags"], inplace=True)
df_unnest_hashtags.reset_index(inplace=True)

In [19]:
df_unnest_mentions = unnest(tweets_df, list(tweets_df.columns.difference(['mentions'])),['mentions'])
df_unnest_mentions["mentions"].replace('', np.nan, inplace=True)
df_unnest_mentions.dropna(how='any', subset=["mentions"], inplace=True)
df_unnest_mentions.reset_index(inplace=True)

In [20]:
def ext_tld(url):
    if not url:
        return [None]*4
    else:
        try:
            path = urlparse(url).path
        except TypeError:
            return [None]*4
        else:
            ext = tldextract.extract(url)
            subdomain = ext.subdomain
            domain = ext.domain
            suffix = ext.suffix
            story = None
            if '-' in path:
                story = "-".join(path.split("-")[:-1]).replace("/","")
            if '@' in path:
                user = path
            
            return subdomain,domain,suffix,story

In [21]:
df_unnest_urls = unnest(tweets_df, list(tweets_df.columns.difference(['urls'])),['urls'])
df_unnest_urls["urls"].replace('', np.nan, inplace=True)
df_unnest_urls.dropna(how='any', subset=["urls"], inplace=True)
df_unnest_urls.reset_index(inplace=True)
df_unnest_urls["subdomain"], df_unnest_urls["domain"], df_unnest_urls["suffix"], df_unnest_urls["story"] = zip(*df_unnest_urls["urls"].apply(ext_tld))
df_unnest_urls["story"].replace('', np.nan, inplace=True)
df_unnest_urls.dropna(how='any', subset=["story"], inplace=True)
df_unnest_urls.reset_index(inplace=True)

In [22]:
_emojis = [emojis for k in UNICODE_EMOJI.keys() for emojis in UNICODE_EMOJI[k].keys() ]
def get_emoji(text):
    l = re.findall(r'[^\w\s,]', text)
    
    return list(set([e for e in l if e in _emojis]))

In [23]:
tweets_df["emojis"] = tweets_df["tweet"].apply(get_emoji)
df_unnest_emojis = unnest(tweets_df, list(tweets_df.columns.difference(['emojis'])),['emojis'])
df_unnest_emojis["emojis"].replace('', np.nan, inplace=True)
df_unnest_emojis.dropna(how='any', subset=["emojis"], inplace=True)
df_unnest_emojis.reset_index(inplace=True)

# Data Modeling

In [24]:
l_hashtags = ["created_at","id","user_id","hashtags","likes_count","retweets_count","replies_count"]
l_urls = ["created_at","id","user_id","urls","domain","subdomain","suffix","story","likes_count","retweets_count","replies_count"]
l_mentions = ["created_at","id","user_id","mentions","likes_count","retweets_count","replies_count"]
l_emojis = ["created_at","id","user_id","emojis","likes_count","retweets_count","replies_count"]
l_users = ["created_at","user_id","username","name"]
l_metrics = ["created_at","id","conversation_id","user_id","likes_count","retweets_count","replies_count","hashtags_count","mentions_count"]

In [25]:
df_unnest_hashtags = df_unnest_hashtags[l_hashtags]
df_unnest_mentions = df_unnest_mentions[l_mentions]
df_unnest_urls = df_unnest_urls[l_urls]
df_unnest_emojis = df_unnest_emojis[l_emojis]
df_metrics = tweets_df[l_metrics]
df_users = tweets_df[l_users]

In [26]:
df_unnest_hashtags = df_unnest_hashtags.reindex(sorted(df_unnest_hashtags.columns), axis=1)
df_unnest_mentions = df_unnest_mentions.reindex(sorted(df_unnest_mentions.columns), axis=1)
df_unnest_urls = df_unnest_urls.reindex(sorted(df_unnest_urls.columns), axis=1)
df_unnest_emojis = df_unnest_emojis.reindex(sorted(df_unnest_emojis.columns), axis=1)
df_metrics = df_metrics.reindex(sorted(df_metrics.columns), axis=1)
df_users = df_users.reindex(sorted(df_users.columns), axis=1)

In [27]:
df_unnest_hashtags.to_csv("data/hashtags.csv",index=False)
df_unnest_mentions.to_csv("data/mentions.csv",index=False)
df_unnest_urls.to_csv("data/urls.csv",index=False)
df_unnest_emojis.to_csv("data/emojis.csv",index=False)
df_metrics.to_csv("data/metrics.csv",index=False)
df_users.to_csv("data/users.csv",index=False)